# Generated by Django 4.2.1 on 2023-05-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_timeoption_remove_dateoptions_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateoptions',
            options={'verbose_name': '예약가능일', 'verbose_name_plural': '예약가능일'},
        ),
        migrations.AlterModelOptions(
            name='timeoption',
            options={'verbose_name': '예약가능시간', 'verbose_name_plural': '예약가능시간'},
        ),
        migrations.AlterField(
            model_name='dateoptions',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='timeoption',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
