# Generated by Django 4.2.1 on 2023-05-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_dateoptions_options_alter_timeoption_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoption',
            name='capacity',
        ),
        migrations.AddField(
            model_name='dateoptions',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
