# Generated by Django 4.2.1 on 2023-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_timeoption_capacity_dateoptions_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateoptions',
            name='time_options',
        ),
        migrations.DeleteModel(
            name='TimeOption',
        ),
        migrations.AddField(
            model_name='dateoptions',
            name='time_options',
            field=models.CharField(default=0, max_length=20, verbose_name='시간'),
        ),
    ]
