# Generated by Django 4.2.1 on 2023-05-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_dateoptions_time_options_delete_timeoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateoptions',
            name='time_options',
        ),
    ]
